# Generated by Django 3.0.7 on 2020-06-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
